# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
author: 9527atct
name: 9527atct
title: 9527ATCT'S HOME
email: lqj_614_19@163.com
description: 9527atct's blog website. my intesting includes machine learning, data mining, and AI. 
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://9527atct.github.io" # the base hostname & protocol for your site
twitter_username: 9527ATCT
github_username:  9527ATCT

# Build settings
markdown: kramdown
