<!-- #include file="bootstrap/bootstrapheader.inc"  -->

<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    extensions: ["tex2jax.js"],
    jax: ["input/TeX", "output/HTML-CSS"],
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
      displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
      processEscapes: true
    },
  });
</script>
<!--MML_HTMLorMML-full-->
<script type="text/javascript" src="./MathJax/MathJax.js?config=TeX-AMS_HTML-full" ></script>
